export const pathRoutes = {
  payment_return: '/payment/vnpay-return',
  payment: '/payment',
  admin: '/admin',
  profile: '/user/profile',
  product_management: '/admin/product-management',
  add_product: '/admin/product-management/add',
  update_product: '/admin/product/manage/:productId',
  home: '/',
  user: '/user',
  changPassword: '/user/password',
  historyPurchase: '/user/purchase',
  login: '/login',
  logout: '/logout',
  register: '/register',
  cart: '/cart',
  productList: '/product-list',
  productDetail: ':nameId',
  account: '/account',
  about: '/about'
}
